services:
  redis:
    container_name: redis
    image: redis:7.4

  eventbus:
    container_name: eventbus
    image: rabbitmq:4.0-management

  postgres:
    container_name: postgres
    image: ankane/pgvector:latest

  identity-api:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}identity-api
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile
    depends_on:
      - postgres
  
  catalog-api:
    container_name: catalog-api
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    depends_on:
      - eventbus
      - postgres

