services:
  redis:
    networks:
      - eshop
    ports:
      - "6379:6379"

  eventbus:
    environment:
      - RABBITMQ_DEFAULT_PASS=senha@123
      - RABBITMQ_DEFAULT_USER=guest
      - HOSTNAME=eventbus
    networks:
      - eshop
    ports:
      - 5672:5672
      - 15672:15672

networks:
  eshop:
    name: eshop
    driver: bridge